# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2446107c92d1014998aeac5e29373817dfee4505fccdcb8200a1a06794e8103d2e814e5ad176783df47a5d048a1fe1d141f1143f2845c66b8ddd980ab9e58f18

test:
  secret_key_base: 68625e829ae67306de4344636b142207c35985f6e1017507199e92e2694e3b6d510d2c79b8a3eee2a919b69c1367518dfc185a810d65455d72ca4780039bf5da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
